### ISSUE TITLE
feature: better error handling system

### ISSUE THREAD

**Issue by garfr** [bonlang/bonc#7]
# Summary

* Error queueing
* Errors represented as their own type, not just as strings
* Automatic generation of code to print errors
* More specific SourcePosition information, and better info propagation

This is a big change and should be broken up into several pull requests.

# Reasoning

Modern compilers should be able to not just accurately report errors in the source program but also report several of them.  How this is achieved varies depending on the phase the compiler is in, but there should be a unified system for queueing up errors to be printed.  The diagnostics should be well defined and not just strings created at runtime and should be able to be easily added and removed.
Writing code to print every error is error-prone, ugly, and very boring.  Instead, a format string, a code generator written in some scripting language, and some magic could be used to automatically generate all the code needed to print error messages.

# Todo

- [ ] Error queueing
- [ ] Errors represented as their own type, not just as strings
- [ ] Automatic generation of code to print errors
- [ ] More specific SourcePosition information, and better info propagation
